feat(workflows): save `pip` and `pre-commit` caches in CI (#224)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -52,6 +52,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -174,6 +176,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Determine Python version
         shell: bash
@@ -289,6 +293,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up Python
         if: startsWith(github.ref, 'refs/tags/')
@@ -315,7 +321,7 @@ jobs:
           PACKAGE_VER="v$(python setup.py --version)"
           RELEASE_TAG="${GITHUB_REF#refs/*/}"
           if [[ "${PACKAGE_VER}" != "${RELEASE_TAG}" ]]; then
-            echo "package ver. (${PACKAGE_VER}) != release tag. (${RELEASE_TAG})"
+            echo "::error::package ver. (${PACKAGE_VER}) != release tag. (${RELEASE_TAG})" >&2
             exit 1
           fi
 
diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -19,6 +19,10 @@ env:
   OPTREE_CXX_WERROR: "ON"
   _GLIBCXX_USE_CXX11_ABI: "1"
   PYTHONUNBUFFERED: "1"
+  XDG_CACHE_HOME: "${{ github.workspace }}/.cache"
+  PIP_CACHE_DIR: "${{ github.workspace }}/.cache/pip"
+  PRE_COMMIT_HOME: "${{ github.workspace }}/.cache/pre-commit"
+  PIP_EXTRA_INDEX_URL: "https://download.pytorch.org/whl/cpu"
 
 jobs:
   lint:
@@ -28,12 +32,23 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up Python 3.12
         uses: actions/setup-python@v5
         with:
           python-version: "3.12"
           update-environment: true
+
+      - name: Set up pip cache
+        id: pip-cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            ${{ env.PIP_CACHE_DIR }}
+            ${{ env.PRE_COMMIT_HOME }}
+          key: ${{ runner.os }}-pip-${{ github.workflow }}-${{ hashFiles('pyproject.toml', '.pre-commit-config.yaml', '**/requirements.txt') }}
 
       - name: Upgrade pip
         run: |
@@ -107,7 +122,7 @@ jobs:
         run: |
           dictionary="$(cat docs/source/spelling_wordlist.txt)"
           if [[ "$(sort --ignore-case <<<"${dictionary}" | uniq)" != "${dictionary}" ]]; then
-            echo "spelling_wordlist.txt is not sorted or contains duplicates" >&2
+            echo "::error::spelling_wordlist.txt is not sorted or contains duplicates" >&2
             exit 1
           fi
           make spelling
diff --git a/.github/workflows/tests-with-pydebug.yml b/.github/workflows/tests-with-pydebug.yml
--- a/.github/workflows/tests-with-pydebug.yml
+++ b/.github/workflows/tests-with-pydebug.yml
@@ -37,6 +37,9 @@ env:
   pybind11_VERSION: "stable"  # to be updated
   PYENV_ROOT: "~/.pyenv"  # to be updated
   COLUMNS: "100"
+  XDG_CACHE_HOME: "${{ github.workspace }}/.cache"
+  PIP_CACHE_DIR: "${{ github.workspace }}/.cache/pip"
+  PIP_EXTRA_INDEX_URL: "https://download.pytorch.org/whl/cpu"
 
 jobs:
   test:
@@ -66,6 +69,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up pyenv (Unix)
         id: setup-pyenv-unix
@@ -134,7 +139,8 @@ jobs:
           fi
           echo "PYTHON_VERSION=${PYTHON_VERSION}" | tee -a "${GITHUB_ENV}"
 
-      - uses: actions/cache@v4
+      - name: Set up pyenv cache
+        uses: actions/cache@v4
         id: pyenv-cache
         with:
           path: ${{ env.PYENV_ROOT }}
@@ -199,6 +205,14 @@ jobs:
           pyenv versions
           pyenv global "$(pyenv versions | grep -F '${{ env.PYTHON_VERSION }}' | tr -d ' ')"
           pyenv rehash
+
+      - name: Set up pip cache
+        id: pip-cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            ${{ env.PIP_CACHE_DIR }}
+          key: ${{ runner.os }}-pip-${{ github.workflow }}-${{ matrix.python-version }}${{ matrix.python-abiflags }}-${{ hashFiles('pyproject.toml', '**/requirements.txt') }}
 
       - name: Set up Environment
         shell: bash
@@ -319,6 +333,9 @@ jobs:
           )
           make test PYTESTOPTS="${PYTESTOPTS[*]}"
           if [[ -n "$(find . -iname "core.*.[1-9]*" -o -iname "core_*.dmp")" ]]; then
+            echo "::error::Coredump files found, indicating a crash during tests." >&2
+            echo "Coredump files:" >&2
+            ls -alh $(find . -iname "core.*.[1-9]*" -o -iname "core_*.dmp") >&2
             exit 1
           fi
 
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -36,6 +36,9 @@ env:
   PYTHON_TAG: "py3"  # to be updated
   pybind11_VERSION: "stable"  # to be updated
   COLUMNS: "100"
+  XDG_CACHE_HOME: "${{ github.workspace }}/.cache"
+  PIP_CACHE_DIR: "${{ github.workspace }}/.cache/pip"
+  PIP_EXTRA_INDEX_URL: "https://download.pytorch.org/whl/cpu"
 
 jobs:
   test:
@@ -59,6 +62,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -66,6 +71,14 @@ jobs:
           python-version: ${{ matrix.python-version }}
           update-environment: true
           allow-prereleases: true
+
+      - name: Set up pip cache
+        id: pip-cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            ${{ env.PIP_CACHE_DIR }}
+          key: ${{ runner.os }}-pip-${{ github.workflow }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml', '**/requirements.txt') }}
 
       - name: Set up Environment
         shell: bash
@@ -250,6 +263,9 @@ jobs:
           )
           make test PYTESTOPTS="${PYTESTOPTS[*]}"
           if [[ -n "$(find . -iname "core.*.[1-9]*" -o -iname "core_*.dmp")" ]]; then
+            echo "::error::Coredump files found, indicating a crash during tests." >&2
+            echo "Coredump files:" >&2
+            ls -alh $(find . -iname "core.*.[1-9]*" -o -iname "core_*.dmp") >&2
             exit 1
           fi
 
