chore(workflows): fetch tags in checkout

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -53,6 +53,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -180,12 +182,14 @@ jobs:
         run: |
           if [[ '${{ env.ALLOW_PRERELEASES }}' != 'true' &&
                 '${{ env.ALLOW_PRERELEASES }}' != 'false' ]]; then
-            echo '::error::Expect ALLOW_PRERELEASES ("${{ env.ALLOW_PRERELEASES }}") to be "true" or "false"'
+            echo '::error::Expect ALLOW_PRERELEASES ("${{ env.ALLOW_PRERELEASES }}") to be "true" or "false"' >&2
             exit 1
           fi
 
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Determine Python version
         shell: bash
@@ -303,6 +307,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up Python
         if: startsWith(github.ref, 'refs/tags/')
@@ -329,7 +335,7 @@ jobs:
           PACKAGE_VER="v$(python setup.py --version)"
           RELEASE_TAG="${GITHUB_REF#refs/*/}"
           if [[ "${PACKAGE_VER}" != "${RELEASE_TAG}" ]]; then
-            echo "package ver. (${PACKAGE_VER}) != release tag. (${RELEASE_TAG})"
+            echo "::error::package ver. (${PACKAGE_VER}) != release tag. (${RELEASE_TAG})" >&2
             exit 1
           fi
 
diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -28,6 +28,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up Python 3.12
         uses: actions/setup-python@v5
@@ -107,7 +109,7 @@ jobs:
         run: |
           dictionary="$(cat docs/source/spelling_wordlist.txt)"
           if [[ "$(sort --ignore-case <<<"${dictionary}" | uniq)" != "${dictionary}" ]]; then
-            echo "spelling_wordlist.txt is not sorted or contains duplicates" >&2
+            echo "::error::spelling_wordlist.txt is not sorted or contains duplicates" >&2
             exit 1
           fi
           make spelling
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -61,6 +61,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -252,6 +254,9 @@ jobs:
           )
           make test PYTESTOPTS="${PYTESTOPTS[*]}"
           if [[ -n "$(find . -iname "core.*.[1-9]*" -o -iname "core_*.dmp")" ]]; then
+            echo "::error::Coredump files found, indicating a crash during tests." >&2
+            echo "Coredump files:" >&2
+            ls -alh $(find . -iname "core.*.[1-9]*" -o -iname "core_*.dmp") >&2
             exit 1
           fi
 
