chore(workflows): add build envvars

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -40,7 +40,7 @@ env:
   PYTHON_TAG: "py3"  # to be updated
   PYTHON_VERSION: "3"  # to be updated
   _GLIBCXX_USE_CXX11_ABI: "1"
-  CIBW_ALLOW_EMPTY: "true"
+  ALLOW_PRERELEASES: "true"
 
 jobs:
   build-sdist:
@@ -175,6 +175,15 @@ jobs:
       fail-fast: false
     timeout-minutes: 180
     steps:
+      - name: Sanity check for variables
+        shell: bash
+        run: |
+          if [[ '${{ env.ALLOW_PRERELEASES }}' != 'true' &&
+                '${{ env.ALLOW_PRERELEASES }}' != 'false' ]]; then
+            echo '::error::Expect ALLOW_PRERELEASES ("${{ env.ALLOW_PRERELEASES }}") to be "true" or "false"'
+            exit 1
+          fi
+
       - name: Checkout
         uses: actions/checkout@v4
 
@@ -191,7 +200,7 @@ jobs:
         with:
           python-version: ${{ env.PYTHON_VERSION }}
           update-environment: true
-          allow-prereleases: true
+          allow-prereleases: ${{ env.ALLOW_PRERELEASES == 'true' }}
 
       - name: Set up Environment
         run: |
@@ -235,7 +244,8 @@ jobs:
           CIBW_BUILD: ${{ env.CIBW_BUILD }}
           CIBW_ARCHS: ${{ matrix.archs }}
           CIBW_ARCHS_MACOS: ${{ matrix.archs }} universal2
-          CIBW_ALLOW_EMPTY: ${{ env.CIBW_ALLOW_EMPTY }}
+          CIBW_ENABLE: pypy cpython-freethreading ${{ env.ALLOW_PRERELEASES == 'true' && 'cpython-prerelease' || '' }}
+          CIBW_ALLOW_EMPTY: ${{ env.ALLOW_PRERELEASES }}
         with:
           package-dir: .
           output-dir: wheelhouse
@@ -245,7 +255,7 @@ jobs:
         with:
           name: wheels-${{ env.PYTHON_TAG }}-${{ runner.os }}-${{ matrix.archs }}
           path: wheelhouse/*.whl
-          if-no-files-found: ${{ env.CIBW_ALLOW_EMPTY == 'true' && 'warn' || 'error' }}
+          if-no-files-found: ${{ env.ALLOW_PRERELEASES == 'true' && 'warn' || 'error' }}
 
   list-artifacts:
     name: List artifacts
@@ -335,7 +345,9 @@ jobs:
         run: ls -lh dist/*
 
       - name: Publish to TestPyPI
-        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
+        if: |
+          (startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch') &&
+          env.ALLOW_PRERELEASES == 'false'
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
           user: __token__
@@ -346,7 +358,9 @@ jobs:
           skip-existing: true
 
       - name: Publish to PyPI
-        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
+        if: |
+          (startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch') &&
+          env.ALLOW_PRERELEASES == 'false'
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
           user: __token__
