chore(workflows/test): enable more debug trace

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -180,25 +180,35 @@ jobs:
         if: runner.os != 'Windows'
         run: |
           (
-            set -x
-            ${{ env.PYTHON }} -m venv venv &&
-            source venv/bin/activate &&
+            set -ex
+            ${{ env.PYTHON }} -m venv venv
+            source venv/bin/activate
             OPTREE_CXX_WERROR=OFF CMAKE_CXX_STANDARD=17 \
-              ${{ env.PYTHON }} -m pip install -v . &&
-            pushd venv &&
-            ${{ env.PYTHON }} -X dev -Walways -Werror -c 'import optree' &&
-            popd &&
+              ${{ env.PYTHON }} -m pip install -v .
+            pushd tests
+            ${{ env.PYTHON }} -X dev -Walways -Werror -c 'import optree'
+            popd
             rm -rf venv
           )
+          if [[ "$?" -ne 0 ]]; then
+            echo "::error::Failed to install with C++17." >&2
+            exit 1
+          fi
+          if [[ -n "$(find . -iname "core.*.[1-9]*" -o -iname "core_*.dmp")" ]]; then
+            echo "::error::Coredump files found, indicating a crash during tests." >&2
+            echo "Coredump files:" >&2
+            ls -alh $(find . -iname "core.*.[1-9]*" -o -iname "core_*.dmp") >&2
+            exit 1
+          fi
 
       - name: Test buildable without Python frontend
         if: runner.os != 'Windows'
         run: |
           (
-            set -x
-            ${{ env.PYTHON }} -m venv venv &&
-            source venv/bin/activate &&
-            make cmake-build && make clean &&
+            set -ex
+            ${{ env.PYTHON }} -m venv venv
+            source venv/bin/activate
+            make cmake-build && make clean
             rm -rf venv
           )
 
@@ -217,20 +227,35 @@ jobs:
         shell: bash
         run: |
           ACTIVATION_SCRIPT="venv/bin/activate"
+          PYTHON_EXE=("${{ env.PYTHON }}")
           if [[ "${{ runner.os }}" == 'Windows' ]]; then
             ACTIVATION_SCRIPT="venv/Scripts/activate"
+            PYTHON_EXE=(
+              cdb -gG -o -c ".dump /ma /u core.dmp; !py; g; q"
+              "${{ env.PYTHON }}"
+            )
           fi
           (
-            set -x
-            ${{ env.PYTHON }} -m venv venv &&
-            source "${ACTIVATION_SCRIPT}" &&
-            ${{ env.PYTHON }} -m pip install -v cmake &&
-            ${{ env.PYTHON }} -m pip install -v . &&
-            pushd venv &&
-            ${{ env.PYTHON }} -X dev -Walways -Werror -c 'import optree' &&
-            popd &&
+            set -ex
+            ${{ env.PYTHON }} -m venv venv
+            source "${ACTIVATION_SCRIPT}"
+            ${{ env.PYTHON }} -m pip install -v cmake
+            ${{ env.PYTHON }} -m pip install -v .
+            pushd tests
+            "${PYTHON_EXE[@]}" -X dev -Walways -Werror -c 'import optree'
+            popd
             rm -rf venv
           )
+          if [[ "$?" -ne 0 ]]; then
+            echo "::error::Failed to install with CMake from PyPI." >&2
+            exit 1
+          fi
+          if [[ -n "$(find . -iname "core.*.[1-9]*" -o -iname "core_*.dmp")" ]]; then
+            echo "::error::Coredump files found, indicating a crash during tests." >&2
+            echo "Coredump files:" >&2
+            ls -alh $(find . -iname "core.*.[1-9]*" -o -iname "core_*.dmp") >&2
+            exit 1
+          fi
 
       - name: Check installable with CMake from PyPI (no system CMake)
         shell: bash
@@ -243,19 +268,34 @@ jobs:
             choco uninstall cmake cmake.install --force --yes || true
           fi
           ACTIVATION_SCRIPT="venv/bin/activate"
+          PYTHON_EXE=("${{ env.PYTHON }}")
           if [[ "${{ runner.os }}" == 'Windows' ]]; then
             ACTIVATION_SCRIPT="venv/Scripts/activate"
+            PYTHON_EXE=(
+              cdb -gG -o -c ".dump /ma /u core.dmp; !py; g; q"
+              "${{ env.PYTHON }}"
+            )
           fi
           (
-            set -x
-            ${{ env.PYTHON }} -m venv venv &&
-            source "${ACTIVATION_SCRIPT}" &&
-            ${{ env.PYTHON }} -m pip install -v . &&
-            pushd venv &&
-            ${{ env.PYTHON }} -X dev -Walways -Werror -c 'import optree' &&
-            popd &&
+            set -ex
+            ${{ env.PYTHON }} -m venv venv
+            source "${ACTIVATION_SCRIPT}"
+            ${{ env.PYTHON }} -m pip install -v .
+            pushd tests
+            "${PYTHON_EXE[@]}" -X dev -Walways -Werror -c 'import optree'
+            popd
             rm -rf venv
           )
+          if [[ "$?" -ne 0 ]]; then
+            echo "::error::Failed to install with CMake from PyPI (no system CMake)." >&2
+            exit 1
+          fi
+          if [[ -n "$(find . -iname "core.*.[1-9]*" -o -iname "core_*.dmp")" ]]; then
+            echo "::error::Coredump files found, indicating a crash during tests." >&2
+            echo "Coredump files:" >&2
+            ls -alh $(find . -iname "core.*.[1-9]*" -o -iname "core_*.dmp") >&2
+            exit 1
+          fi
 
       - name: Test with pytest
         shell: bash
